use_frameworks!

platform :ios, '11.0'
	
source "https://github.com/lightningkite/cocoapods-spec-repo.git"
source "https://cdn.cocoapods.org"

target 'RxSwiftPlus_Example' do
  pod 'RxSwiftPlus', :path => '../'

  target 'RxSwiftPlus_Tests' do
    inherit! :search_paths
  end
  
  pod 'XmlToXibRuntime'
  pod 'KhrysalisRuntime'
  pod "RxCoreLocation"
  pod "RxBluetoothKit", :git => 'https://github.com/lightningkite/RxBluetoothKit.git', :tag => '7.0.5'
end

post_install do |installer|
  installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
             end
        end
 end
end
