use_frameworks!

platform :ios, '12.0'
	
source "https://github.com/lightningkite/cocoapods-spec-repo.git"
source "https://cdn.cocoapods.org"

target 'RxSwiftPlus_Example' do
  pod 'RxSwiftPlus', :path => '../'

  target 'RxSwiftPlus_Tests' do
    inherit! :search_paths
  end
  
  pod 'XmlToXibRuntime'
  pod 'KhrysalisRuntime'
  pod "RxCoreLocation"
  pod "RxBluetoothKit"
end

