use_frameworks!

platform :ios, '11.0'

target 'RxSwiftProperty_Example' do
  pod 'RxSwiftProperty', :path => '../'

  target 'RxSwiftProperty_Tests' do
    inherit! :search_paths
    
  end
  pod 'XmlToXibRuntime', :path => '../../XmlToXibRuntime/XmlToXibRuntime.podspec'
  pod 'KhrysalisRuntime', :path => '../../khrysalis/ios-runtime/KhrysalisRuntime/KhrysalisRuntime.podspec'
  pod "RxCoreLocation", :git => 'https://github.com/RxSwiftCommunity/RxCoreLocation.git', :branch => 'master'
end
